name: unit-test

on:
  pull_request:

  workflow_dispatch:

jobs:
  unittest:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set python version to 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run unit tests
        run:
          pytest
